### ISSUE TITLE
Siblings selection should be random or based on data availability 

### ISSUE THREAD

**Issue by SereDef** [VilteB/ELS_and_PCM_ALSPAC#4]
https://github.com/VilteB/ELS_and_PCM/blob/19a42a540dfa16159bb086bf1c52a0ae80cf0bbe/2.1.Prenatal_ELS_collapsed.R#L22

This is a minor point but the line selects only the first borns right? In my version I perform the exclusion based on data availability or randomly

**Comment by VilteBaltra** [comment]
The code has now been updated to select based on data availability.
